export default {
        reloaded: false,
        role: '',
        connection: null,
        msg: 'exec=1',
        test: "346",
        EnergyStorageModeControl: 0,
        chDischPwr1: 0,
        /*
        Energy_Storage_Mode_Control
        Energy storage operating mode setting.
        0: Self-generating and self-consumption mode
        1: time-sharing tariff mode
        2: Timed charging and discharging mode
        3: Passive mode
        4: Peak-shaving mode
        Used to change the operating mode.
        */
        ActivePower_Output_TotalStr: "111",
        // SysState: null,
        // Frequency_Grid: null,
        // ActivePower_Output_Total: null,
        // ReactivePower_Output_Total: null,
        // ApparentPower_Output_Total: null,
        // ActivePower_PCC_Total: null,
        // ReactivePower_PCC_Total: null,
        // ApparentPower_PCC_Total: null,
        // GridOutput_Rsvd1: null,
        // GridOutput_Rsvd2: null,
        // Voltage_Phase_R: null,
        // Voltage_Phase_S: null,
        // Voltage_Phase_T: null,
        // Current_Output_R: null,
        // Current_Output_S: null,
        // Current_Output_T: null,
        // ActivePower_Output_R: null,
        // ActivePower_Output_S: null,
        // ActivePower_Output_T: null,
        // ReactivePower_Output_R: null,
        // ReactivePower_Output_S: null,
        // ReactivePower_Output_T: null,
        // PowerFactor_Output_R: null,
        // PowerFactor_Output_S: null,
        // PowerFactor_Output_T: null,
        // Current_PCC_R: null,
        // Current_PCC_S: null,
        // Current_PCC_T: null,
        // ActivePower_PCC_R: null,
        // ActivePower_PCC_S: null,
        // ActivePower_PCC_T: null,
        // ReactivePower_PCC_R: null,
        // ReactivePower_PCC_S: null,
        // ReactivePower_PCC_T: null,
        // PowerFactor_PCC_R: null,
        // PowerFactor_PCC_S: null,
        // PowerFactor_PCC_T: null,
        // R_Rsvd1: null,
        // R_Rsvd2: null,
        // S_Rsvd1: null,
        // S_Rsvd2: null,
        // T_Rsvd1: null,
        // T_Rsvd2: null,
        // ActivePower_PV_Ext: null,
        // ActivePower_Load_Sys: null,
        // ActivePower_Load_Total: null,
        // Frequency_Output: null,
        // Voltage_Output_R: null,
        // Current_Load_R: null,
        // Active_Power_Load_R: null,
        // Voltage_Output_S: null,
        // Current_Load_S: null,
        // Active_Power_Load_S: null,
        // Voltage_Output_T: null,
        // Current_Load_T: null,
        // Active_Power_Load_T: null,
        // Voltage_Phase_L1N: null,
        // Current_Output_L1N: null,
        // ActivePower_Output_L1N: null,
        // Current_PCC_L1N: null,
        // ActivePower_PCC_L1N: null,
        // Voltage_Phase_L2N: null,
        // Current_Output_L2N: null,
        // ActivePower_Output_L2N: null,
        // Current_PCC_L2N: null,
        // ActivePower_PCC_L2N: null,
        // Voltage_Line_L1: null,
        // Voltage_Line_L2: null,
        // Voltage_Line_L3: null,
        // Voltage_PV1: null,
        // Voltage_PV2: null,
        // Current_PV1: null,
        // Current_PV2: null,
        // Power_PV1: null,
        // Power_PV2: null,
        // Voltage_Bat1: null,
        // Voltage_Bat2: null,
        // Current_Bat1: null,
        // Current_Bat2: null,
        // Power_Bat1: null,
        // Power_Bat2: null,
        // Temperature_Env_Bat1: null,
        // Temperature_Env_Bat2: null,
        // SOC_Bat1: null,
        // SOC_Bat2: null,
        // SOH_Bat1: null,
        // SOH_Bat2: null,
        // ChargeCycle_Bat1: null,
        // ChargeCycle_Bat2: null,
        // PV_Generation_Today: null,
        // PV_Generation_Total: null,
        // Load_Consumption_Today: null,
        // Load_Consumption_Total: null,
        // Energy_Purchase_Today: null,
        // Energy_Purchase_Total: null,
        // Energy_Selling_Today: null,
        // Energy_Selling_Total: null,
        // Bat_Charge_Today: null,
        // Bat_Charge_Total: null,
        // Bat_Discharge_Today: null,
        // Bat_Discharge_Total: null,
        // inverterStatus: null,
        // Countdoun: null,
        // Temperature_Env1: null,
        // Temperature_Env2: null,
        // Temperature_HeatSink1: null,
        // Temperature_HeatSink2: null,
        // Temperature_HeatSink3: null,
        // Temperature_HeatSink4: null,
        // Temperature_HeatSink5: null,
        // Temperature_HeatSink6: null,
        // Temperature_Inv1: null,
        // Temperature_Inv2: null,
        // Temperature_Inv3: null,
        // Temp_Rsvd1: null,
        // Temp_Rsvd2: null,
        // Temp_Rsvd3: null,
        // GenerationTime_Today: null,
        // GenerationTime_Total: null,
        // ServiceTime_Total: null,
        // InsulationResistance: null,
        // InsulationResistance: null,
        // SysTime_Year: null,
        // SysTime_Month: null,
        // SysTime_Month_Str: "",
        // SysTime_Date: null,
        // SysTime_Date_Str: "",
        // SysTime_Hour: null,
        // SysTime_Hour_Str: "",
        // SysTime_Minute: null,
        // SysTime_Minute_Str: "",
        // SysTime_Second: null,
        // SysTime_Second_Str: "",
        
        // fault1: null,
        // fault2: null,
        // fault3: null,
        // fault4: null,
        // fault5: null,
        // fault6: null,
        // fault7: null,
        // fault8: null,
        // fault9: null,
        // fault10: null,
        // fault11: null,
        // fault12: null,
        // fault13: null,
        // fault14: null,
        // fault15: null,
        // fault16: null,
        // fault17: null,
        // fault18: null,
        // alarm8: false,
        // faultTest8: null,
        // alarmTest: false,
        // testAlarm: 0b0000000000000010,
        // overtemperatureDeratingString: "Overtemperature derating OK"   

        // sysinfo1
        inverterStatus: null,
        Countdown: null,
        Temperature_Env1: null,
        Temperature_Env2: null,
        Temperature_HeatSink1: null,
        Temperature_HeatSink2: null,
        Temperature_HeatSink3: null,
        Temperature_HeatSink4: null,
        Temperature_HeatSink5: null,
        Temperature_HeatSink6: null,
        Temperature_Inv1: null,
        Temperature_Inv2: null,
        Temperature_Inv3: null,
        Temp_Rsvd1: null,
        Temp_Rsvd2: null,
        Temp_Rsvd3: null,
        GenerationTime_Today: null,
        GenerationTime_Total: null,
        ServiceTime_Total: null,
        InsulationResistance: null,
        SysTime_Year: null,
        SysTime_Month: null,
        SysTime_Month_Str: "",
        SysTime_Date: null,
        SysTime_Date_Str: "",
        SysTime_Hour: null,
        SysTime_Hour_Str: "",
        SysTime_Minute: null,
        SysTime_Minute_Str: "",
        SysTime_Second: null,
        SysTime_Second_Str: "",
        // Sysinfo2
        loggerSN: "",
        Production_Code: "",
        Serial_Number: "",
        Hardware_Version: "",
        Software_Version_Stage_COM: "",
        Software_Version_Major_COM: "",
        Software_Version_Custom_COM: "",
        Software_Version_Minor_COM: "",
        Software_Version_Stage_Master: "",
        Software_Version_Custom_Master: "",
        Software_Version_Minor_Master: "",
        Software_Version_COM: "",
        Software_Version_Master: "",
        Software_Version_Slave: "",
        Safety_Version_Major: "",
        // errors
        fault1: null,
        fault2: null,
        fault3: null,
        fault4: null,
        fault5: null,
        fault6: null,
        fault7: null,
        fault8: null,
        fault9: null,
        fault10: null,
        fault11: null,
        fault12: null,
        fault13: null,
        fault14: null,
        fault15: null,
        fault16: null,
        fault17: null,
        fault18: null,
        fault19: null,
        fault20: null,
        fault21: null,
        fault22: null,
        fault23: null,
        fault24: null,
        fault25: null,
        fault26: null,
        fault27: null,
        // grid
        Frequency_Grid: null,
        ActivePower_Output_Total: null,
        ReactivePower_Output_Total: null,
        ApparentPower_Output_Total: null,
        ActivePower_PCC_Total: null,
        ReactivePower_PCC_Total: null,
        ApparentPower_PCC_Total: null,
        GridOutput_Rsvd1: null,
        GridOutput_Rsvd2: null,
        Voltage_Phase_R: null,
        Current_Output_R: null,
        ActivePower_Output_R: null,
        ReactivePower_Output_R: null,
        PowerFactor_Output_R: null,
        Current_PCC_R: null,
        ActivePower_PCC_R: null,
        ReactivePower_PCC_R: null,
        PowerFactor_PCC_R: null,
        R_Rsvd1: null,
        R_Rsvd2: null,
        Voltage_Phase_S: null,
        Current_Output_S: null,
        ActivePower_Output_S: null,
        ReactivePower_Output_S: null,
        PowerFactor_Output_S: null,
        Current_PCC_S: null,
        ActivePower_PCC_S: null,
        ReactivePower_PCC_S: null,
        PowerFactor_PCC_S: null,
        S_Rsvd1: null,
        S_Rsvd2: null,
        Voltage_Phase_T: null,
        Current_Output_T: null,
        ActivePower_Output_T: null,
        ReactivePower_Output_T: null,
        PowerFactor_Output_T: null,
        Current_PCC_T: null,
        ActivePower_PCC_T: null,
        ReactivePower_PCC_T: null,
        PowerFactor_PCC_T: null,
        T_Rsvd1: null,
        T_Rsvd2: null,
        ActivePower_PV_Ext: null,
        ActivePower_Load_Sys: null,
        Voltage_Phase_L1N: null,
        Current_Output_L1N: null,
        ActivePower_Output_L1N: null,
        Current_PCC_L1N: null,
        ActivePower_PCC_L1N: null,
        Voltage_Phase_L2N: null,
        Current_Output_L2N: null,
        ActivePower_Output_L2N: null,
        Current_PCC_L2N: null,
        ActivePower_PCC_L2N: null,
        Voltage_Line_L1: null,
        Voltage_Line_L2: null,
        Voltage_Line_L3: null,
        // EmergencyOutput1
        ActivePower_Load_Total: null,
        ReactivePower_Load_Total: null,
        ApparentPower_Load_Total: null,
        Frequency_Output: null,
        ESOutput_Rsvd1: null,
        ESOutput_Rsvd2: null,
        Voltage_Output_R: null,
        Current_Load_R: null,
        ActivePower_Load_R: null,
        ReactivePower_Load_R: null,
        ApparentPower_Load_R: null,
        LoadPeakRatio_R: null,
        ESR_Rsvd1: null,
        ESR_Rsvd2: null,
        Voltage_Output_S: null,
        Current_Load_S: null,
        ActivePower_Load_S: null,
        ReactivePower_Load_S: null,
        ApparentPower_Load_S: null,
        LoadPeakRatio_S: null,
        ESS_Rsvd1: null,
        ESS_Rsvd2: null,
        Voltage_Output_T: null,
        Current_Load_T: null,
        ActivePower_Load_T: null,
        ReactivePower_Load_T: null,
        ApparentPower_Load_T: null,
        LoadPeakRatio_T: null,
        EST_Rsvd2: null,
        Voltage_Output_L1N: null,
        Current_Load_L1N: null,
        ActivePower_Load_L2N: null,
        // Input_PV1
        Voltage_PV1: null,
        Current_PV1: null,
        Power_PV1: null,
        Voltage_PV2: null,
        Current_PV2: null,
        Power_PV2: null,
        Voltage_PV3: null,
        Current_PV3: null,
        Power_PV3: null,
        Voltage_PV3: null,
        Current_PV3: null,
        Power_PV3: null,
        Voltage_PV4: null,
        Current_PV4: null,
        Power_PV4: null,
        Voltage_PV5: null,
        Current_PV5: null,
        Power_PV5: null,
        Voltage_PV6: null,
        Current_PV6: null,
        Power_PV6: null,
        Voltage_PV7: null,
        Current_PV7: null,
        Power_PV7: null,
        Voltage_PV8: null,
        Current_PV8: null,
        Power_PV8: null,
        Voltage_PV9: null,
        Current_PV9: null,
        Power_PV9: null,
        Voltage_PV10: null,
        Current_PV10: null,
        Power_PV10: null,
        Voltage_PV11: null,
        Current_PV11: null,
        Power_PV11: null,
        Voltage_PV12: null,
        Current_PV12: null,
        Power_PV12: null,
        Voltage_PV13: null,
        Current_PV13: null,
        Power_PV13: null,
        Voltage_PV14: null,
        Current_PV14: null,
        Power_PV14: null,
        Voltage_PV10: null,
        Current_PV10: null,
        Power_PV10: null,
        Voltage_PV11: null,
        Current_PV11: null,
        Power_PV11: null,
        Voltage_PV12: null,
        Current_PV12: null,
        Power_PV12: null,
        Voltage_PV13: null,
        Current_PV13: null,
        Power_PV13: null,
        Voltage_PV14: null,
        Current_PV14: null,
        Power_PV14: null,
        Voltage_PV15: null,
        Current_PV15: null,
        Power_PV15: null,
        Voltage_PV16: null,
        Current_PV16: null,
        Power_PV16: null,
        Voltage_PV17: null,
        Current_PV17: null,
        Power_PV17: null,
        Voltage_PV18: null,
        Current_PV18: null,
        Power_PV18: null,
        Voltage_PV19: null,
        Current_PV19: null,
        Power_PV19: null,
        // ElectricityStatistics1
        PV_Generation_Today: null,
        PV_Generation_Total: null,
        Load_Consumption_Today: null,
        Load_Consumption_Total: null,
        Energy_Purchase_Today: null,
        Energy_Purchase_Total: null,
        Energy_Selling_Today: null,
        Energy_Selling_Total: null,
        Bat_Charge_Today: null,
        Bat_Charge_Total: null,
        Bat_Discharge_Today: null,
        Bat_Discharge_Total: null,
        // ClassifiedInfo1
        GFCI: null,
        Current_Bus_Balance: null,
        DCI_R: null,
        DCI_S: null,
        DCI_T: null,
        DCV_R: null,
        DCV_S: null,
        DCV_T: null,
        Voltage_Bus: null,
        Voltage_Bus_P: null,
        Voltage_Bus_N: null,
        Voltage_Bus_LLC: null,
        Current_BuckBoost: null,
        Voltage_Bus_P_Half: null,
        Voltage_Bus_N_Half: null,
        // Input_Bat1
        Voltage_Bat1: null,
        Current_Bat1: null,
        Power_Bat1: null,
        Temperature_Env_Bat1: null,
        SOC_Bat1: null,
        SOH_Bat1: null,
        ChargeCycle_Bat1: null,
        // Input_Bat2
        Voltage_Bat2: null,
        Current_Bat2: null,
        Power_Bat2: null,
        Temperature_Env_Bat2: null,
        SOC_Bat2: null,
        SOH_Bat2: null,
        ChargeCycle_Bat2: null,
}
